######################## default configuration ####################
baseURL = "https://zealous-river-0e56eb810.1.azurestaticapps.net"
title = "Inuvialuit Regional Corporation Data Catalog"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com


[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.min.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.css]]
link = "https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"

############################# Params ##############################
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.min.js"
[[params.plugins.js]]
link = "plugins/rellax/rellax.min.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"
[[params.plugins.js]]
link = "https://unpkg.com/itemsjs@latest/dist/itemsjs.min.js"
[[params.plugins.js]]
link = "https://unpkg.com/vue@3"
[[params.plugins.js]]
link = "https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.83.1"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]

[imaging]
quality = 90

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
