# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Topics"
url = "topics/"
weight = 3

[[main]]
name = "Datasets"
url = "catalogues/"
weight = 4
 
[[main]]
name = "Contact"
url = "contact/"
weight = 5

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4