# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Search"
url = "search/"
weight = 2

[[main]]
name = "Datasets"
url = "catalogues/"
weight = 4

# footer menu
[[footer]]
name = "Search"
url = "search/"
weight = 1